const subsidiary = [
  { value: "Aix-en-Provence", label: "Aix-en-Provence" },
  { value: "Aveiro", label: "Aveiro" },
  { value: "Bordeaux", label: "Bordeaux" },
  { value: "Brest", label: "Brest" },
  { value: "Bruxelles", label: "Bruxelles" },
  { value: "Canada", label: "Canada" },
  { value: "Casablanca", label: "Casablanca" },
  { value: "Clermont-Ferrand", label: "Clermont-Ferrand" },
  { value: "Dijon", label: "Dijon" },
  { value: "Genève", label: "Genève" },
  { value: "Le Mans", label: "Le Mans" },
  { value: "Lille", label: "Lille" },
  { value: "Lyon", label: "Lyon" },
  { value: "Montpellier", label: "Montpellier" },
  { value: "Munich", label: "Munich" },
  { value: "Nice - Sophia Antipolis", label: "Nice - Sophia Antipolis" },
  { value: "Nantes", label: "Nantes" },
  { value: "Niort", label: "Niort" },
  { value: "Orléans", label: "Orléans" },
  { value: "Paris", label: "Paris" },
  { value: "Rennes", label: "Rennes" },
  { value: "Strasbourg", label: "Strasbourg" },
  { value: "Toulouse", label: "Toulouse" },
  { value: "Tours", label: "Tours" },
  { value: "Vernon", label: "Vernon" },
];

export default subsidiary;
